name: Verify Tests

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ./bin and ./output directories
        run: mkdir -p ./bin ./output

      - name: Build Flower
        working-directory: .
        env:
          ASAN_OPTIONS: detect_leaks=0:abort_on_error=0:strict_string_checks=0
        run:  |
          pwd
          ls -la /home/runner/work/flower/flower/examples/memory/memory.flo
          gcc \
            -fsanitize=address \
            -fno-omit-frame-pointer \
            -g \
            -O0 \
            -Wall \
            -Wextra \
            ./bin/Flower.c \
            -o ./bin/Flower
          ./bin/Flower ./src/main.flo ./bin/Flower

      - name: Run Tests
        run: |
          pwd
          ls -la examples/memory/memory.flo
          ./bin/Flower ./examples/test.flo ./output/out